package builder

import (
	"fmt"
	"os"
	"slices"

	"gopkg.in/yaml.v3"
)

func BuildConfig(userSelection *UserSelection) error {
	err := setupOutputFolder()
	if err != nil {
		return err
	}

	err = buildEventLogConfig(userSelection)
	if err != nil {
		return err
	}

	err = buildEventStreamConfig(userSelection)
	if err != nil {
		return err
	}

	return nil
}

func buildEventLogConfig(userSelection *UserSelection) error {
	eventLogConf := EventLogConfigFileModel{
		Version: "2.0",
		EventLog: EventLog{
			InstanceName: "sfdc-instance-1",
			ApiVer:       "64.0", // The minimum SFDC API version that supports all the event types we collect
			Auth: Auth{
				TokenUrl: userSelection.Salesforce.TokenUrl,
			},
			EventTypes: buildEventTypes(userSelection.Groups),
		},
		RunAsService: userSelection.RunMode == ServiceMode,
		LicenseKey:   "SET THE NEW RELIC LICENSE KEY HERE",
		AccountId:    userSelection.NewRelic.AccountId,
		Region:       userSelection.NewRelic.Region,
		Format:       "events",
	}

	switch userSelection.Salesforce.AuthSelection {
	case Jwt:
		eventLogConf.EventLog.Auth.Jwt = &JwtAuth{
			ClientId:   "SET CLIENT ID HERE",
			PrivateKey: "SET PRIVATE KEY HERE",
			Username:   "SET USER NAME HERE",
		}
	case ClientCred:
		eventLogConf.EventLog.Auth.ClientCred = &ClientCredAuth{
			ClientId:     "SET CLIENT ID HERE",
			ClientSecret: "SET CLIENT SECRET HERE",
		}
	case UserPass:
		eventLogConf.EventLog.Auth.UserPass = &UserPassAuth{
			ClientId:     "SET CLIENT ID HERE",
			ClientSecret: "SET CLIENT SECRET HERE",
			Username:     "SET USER NAME HERE",
			Password:     "SET PASSWORD HERE",
		}
	default:
		return fmt.Errorf("Unknown auth method selection")
	}

	if userSelection.Redis != nil {
		eventLogConf.EventLog.Cache = &Cache{
			Redis: &RedisCache{
				Host:       userSelection.Redis.Host,
				Port:       userSelection.Redis.Port,
				DbNumber:   userSelection.Redis.DbNum,
				Password:   userSelection.Redis.Password,
				ExpireDays: 1,
			},
		}
	}

	eventLogConfYaml, err := yaml.Marshal(&eventLogConf)
	if err != nil {
		return err
	}

	eventLogConfFile, err := os.OpenFile(
		BuildInstallerPath("config_eventlog.yml"),
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0600,
	)
	if err != nil {
		return err
	}
	_, err = eventLogConfFile.WriteString("# Config file for the eventlog integration. Autogenerated with the Intaller Tool.\n\n")
	if err != nil {
		return err
	}
	_, err = eventLogConfFile.WriteString(string(eventLogConfYaml))
	if err != nil {
		return err
	}
	err = eventLogConfFile.Close()
	if err != nil {
		return err
	}

	return nil
}

func buildEventTypes(eventGroups []EventGroup) []string {
	eventTypes := []string{}
	for _, eventId := range eventGroups {
		switch eventId {
		case UserAccess:
			eventTypes = append(eventTypes,
				"Login",
				"LoginAs",
				"Logout",
			)
		case ApexUsage:
			eventTypes = append(eventTypes,
				"ApexCallout",
				"ApexExecution",
				"ApexRestApi",
				"ApexSoap",
				"ApexTrigger",
				"ApexUnexpectedException",
				"AuraRequest",
				"ConcurrentLongRunningApexLimit",
				"ExternalCustomApexCallout",
				"NamedCredential",
			)
		case LightningUsage:
			eventTypes = append(eventTypes,
				"LightningError",
				"LightningInteraction",
				"LightningLogger",
				"LightningPageView",
				"LightningPerformance",
				"VisualforceRequest",
			)
		case ApiAccess:
			eventTypes = append(eventTypes,
				"ApiTotalUsage",
				"BulkApi",
				"BulkApiRequest",
				"BulkApi2",
				"CompositeApi",
				"CompositeApiSubrequest",
				"MetadataApiOperation",
				"RestApi",
				"API", // SOAP API
			)
		case ReportAccess:
			eventTypes = append(eventTypes,
				"AsynchronousReportRun",
				"Dashboard",
				"MultiblockReport",
				"Report",
				"ReportExport",
			)
		case DocContentDbAccess:
			eventTypes = append(eventTypes,
				"DatabaseSave",
				"UniqueQuery",
				"DocumentAttachmentDownoads",
				"ContentDocumentLink",
				"ContentTransfer",
				"ContentDistribution",
			)
		case WaveUsage:
			eventTypes = append(eventTypes,
				"WaveChange",
				"WaveDownload",
				"WaveInteraction",
				"WavePerformance",
			)
		case ErrPermViol:
			eventTypes = append(eventTypes,
				"CorsViolation",
				"CspViolation",
				"InsufficientAccess",
				"PermissionUpdate",
				"InsecureExternalAssets",
				"TransactionSecurity",
				"BlockedRedirect",
				"HostnameRedirects",
				"GroupMembership",
			)
		}
	}
	return eventTypes
}

func buildEventStreamConfig(userSelection *UserSelection) error {
	alertSecurityGroup := slices.Contains(userSelection.Groups, AlertSecurity)
	if !alertSecurityGroup {
		return nil
	}
	eventStreamConf := EventStreamConfigFileModel{
		Version: "2.0",
		EventStream: EventStream{
			InstanceName: "sfdc-instance-1",
			Auth: Auth{
				TokenUrl: userSelection.Salesforce.TokenUrl,
				// Ignore auth selection, event stream only supports User-Pass flow
				UserPass: &UserPassAuth{
					ClientId:     "SET CLIENT ID HERE",
					ClientSecret: "SET CLIENT SECRET HERE",
					Username:     "SET USER NAME HERE",
					Password:     "SET PASSWORD HERE",
				},
			},
			Appetite: 50,
			Topics: []string{
				"/event/LoginAnomalyEvent",
				"/event/SessionHijackingEvent",
				"/event/CredentialStuffingEvent",
			},
		},
		LicenseKey: "SET THE NEW RELIC LICENSE KEY HERE",
		AccountId:  userSelection.NewRelic.AccountId,
		Region:     userSelection.NewRelic.Region,
		Format:     "events",
	}

	if userSelection.Redis != nil {
		eventStreamConf.EventStream.Cache = &Cache{
			Redis: &RedisCache{
				Host:       userSelection.Redis.Host,
				Port:       userSelection.Redis.Port,
				DbNumber:   userSelection.Redis.DbNum,
				Password:   userSelection.Redis.Password,
				ExpireDays: 1,
			},
		}
	}

	eventStreamConfYaml, err := yaml.Marshal(&eventStreamConf)
	if err != nil {
		return err
	}

	eventLogConfFile, err := os.OpenFile(
		BuildInstallerPath("config_eventstream.yml"),
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0600,
	)
	if err != nil {
		return err
	}
	_, err = eventLogConfFile.WriteString("# Config file for the eventstream integration. Autogenerated with the Intaller Tool.\n\n")
	if err != nil {
		return err
	}
	_, err = eventLogConfFile.WriteString(string(eventStreamConfYaml))
	if err != nil {
		return err
	}
	err = eventLogConfFile.Close()
	if err != nil {
		return err
	}

	return nil
}

func setupOutputFolder() error {
	os.MkdirAll(InstallerPath(), os.ModePerm)
	f, err := os.OpenFile(
		BuildInstallerPath(".gitignore"),
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0644,
	)
	if err != nil {
		return err
	}
	_, err = f.WriteString("*")
	if err != nil {
		return err
	}
	err = f.Close()
	if err != nil {
		return err
	}
	return nil
}
