package builder

import (
	"os"
	"strings"
)

var eventLogDocker = []string{
	"FROM golang:1.25.3-alpine3.22 AS build-stage",
	"WORKDIR /build",
	"COPY go.mod go.sum ./",
	"RUN go mod download",
	"COPY cmd ./cmd",
	"COPY internal ./internal",
	"RUN CGO_ENABLED=0 go build ./cmd/nr-salesforce-eventlog/nr-salesforce-eventlog.go",
	"FROM alpine:3.22 AS release-stage",
	"WORKDIR /app",
	"COPY --from=build-stage /build/nr-salesforce-eventlog ./",
	"COPY config_eventlog.yml ./",
	"CMD [\"./nr-salesforce-eventlog\"]",
}

var eventStreamDocker = []string{
	"FROM golang:1.25.3-alpine3.22 AS build-stage",
	"WORKDIR /build",
	"COPY go.mod go.sum ./",
	"RUN go mod download",
	"COPY cmd ./cmd",
	"COPY internal ./internal",
	"RUN CGO_ENABLED=0 go build ./cmd/nr-salesforce-stream/nr-salesforce-stream.go",
	"FROM alpine:3.22 AS release-stage",
	"WORKDIR /app",
	"COPY --from=build-stage /build/nr-salesforce-stream ./",
	"COPY config_eventstream.yml ./",
	"CMD [\"./nr-salesforce-stream\"]",
}

func BuildDocker() error {
	err := buildEventLogDocker()
	if err != nil {
        return err
    }

	err = buildEventStreamDocker()
	if err != nil {
        return err
    }

	return nil
}

func buildEventLogDocker() error {
	eventLogDockerfile, err := os.OpenFile(
		buildInstallerPath("Dockerfile.eventlog"),
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0600,
	)
    if err != nil {
        return err
    }
	_, err = eventLogDockerfile.WriteString("# Dockerfile for the eventlog integration. Autogenerated with the Intaller Tool.\n\n")
	if err != nil {
        return err
    }
	_, err = eventLogDockerfile.WriteString(strings.Join(eventLogDocker, "\n\n"))
	if err != nil {
        return err
    }
	err = eventLogDockerfile.Close()
	if err != nil {
        return err
    }
	return nil
}

func buildEventStreamDocker() error {
	eventStreamDockerfile, err := os.OpenFile(
		buildInstallerPath("Dockerfile.eventstream"),
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0600,
	)
    if err != nil {
        return err
    }
	_, err = eventStreamDockerfile.WriteString("# Dockerfile for the eventstream integration. Autogenerated with the Intaller Tool.\n\n")
	if err != nil {
        return err
    }
	_, err = eventStreamDockerfile.WriteString(strings.Join(eventStreamDocker, "\n\n"))
	if err != nil {
        return err
    }
	err = eventStreamDockerfile.Close()
	if err != nil {
        return err
    }
	return nil
}