package builder

import (
	"os"
	"slices"
	"strings"
)

var eventLogDocker = []string{
	"FROM newrelic/newrelic-salesforce-exporter",
	"COPY installer_output/config_eventlog.yml ./config.yml",
	"CMD [\"./nr-salesforce-eventlog\"]",
}

var eventStreamDocker = []string{
	"FROM newrelic/newrelic-salesforce-exporter",
	"COPY installer_output/config_eventstream.yml ./config.yml",
	"CMD [\"./nr-salesforce-stream\"]",
}

func BuildDocker(userSelection *UserSelection) error {
	err := buildEventLogDocker()
	if err != nil {
		return err
	}

	alertSecurityGroup := slices.Contains(userSelection.Groups, AlertSecurity)
	if !alertSecurityGroup {
		return nil
	}

	err = buildEventStreamDocker()
	if err != nil {
		return err
	}

	return nil
}

func buildEventLogDocker() error {
	eventLogDockerfile, err := os.OpenFile(
		BuildInstallerPath("Dockerfile.eventlog"),
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0600,
	)
	if err != nil {
		return err
	}
	_, err = eventLogDockerfile.WriteString("# Dockerfile for the eventlog integration. Autogenerated with the Installer Tool.\n\n")
	if err != nil {
		return err
	}
	_, err = eventLogDockerfile.WriteString(strings.Join(eventLogDocker, "\n\n"))
	if err != nil {
		return err
	}
	err = eventLogDockerfile.Close()
	if err != nil {
		return err
	}
	return nil
}

func buildEventStreamDocker() error {
	eventStreamDockerfile, err := os.OpenFile(
		BuildInstallerPath("Dockerfile.eventstream"),
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0600,
	)
	if err != nil {
		return err
	}
	_, err = eventStreamDockerfile.WriteString("# Dockerfile for the eventstream integration. Autogenerated with the Installer Tool.\n\n")
	if err != nil {
		return err
	}
	_, err = eventStreamDockerfile.WriteString(strings.Join(eventStreamDocker, "\n\n"))
	if err != nil {
		return err
	}
	err = eventStreamDockerfile.Close()
	if err != nil {
		return err
	}
	return nil
}
