package builder

import (
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

func BuildConfig(userSelection UserSelection) error {
	err := setupOutputFolder()
	if err != nil {
		return err
	}

	err = buildEventLogConfig(&userSelection)
	if err != nil {
		return err
	}

	// TODO: build config file for Event Stream integration

	return nil
}

func buildEventLogConfig(userSelection *UserSelection) error {
	eventLogConf := EventLogConfigFileModel{
		Version: "2.0",
		EventLog: EventLog{
			IntegrationName: "com.newrelic.labs.sfdc.eventlog",
			Instances: []Instance{
				{
					Name: "sfdc-instance-1",
					Auth: Auth{
						TokenUrl: userSelection.Salesforce.TokenUrl,
						UserPass: UserPass{
							ClientId: userSelection.Salesforce.ClientId,
							ClientSecret: userSelection.Salesforce.ClientSecret,
							Username: userSelection.Salesforce.Username,
							Password: userSelection.Salesforce.Password,
						},
					},
					EventTypes: buildEventTypes(userSelection.Groups),
				},
			},
		},
		RunAsService: userSelection.RunMode == ServiceMode,
		LicenseKey: userSelection.NewRelic.ApiKey,
		AccountId: userSelection.NewRelic.AccountId,
		Region: userSelection.NewRelic.Region,
		Format: "events",
	}

	if userSelection.Redis != nil {
		eventLogConf.EventLog.Instances[0].Cache = &Cache{
			Redis: &RedisCache{
				Host: userSelection.Redis.Host,
				Port: userSelection.Redis.Port,
				DbNumber: userSelection.Redis.DbNum,
				Password: userSelection.Redis.Password,
				ExpireDays: 1,
			},
		}
	}

	eventLogConfYaml, err := yaml.Marshal(&eventLogConf)
	if err != nil {
		return err
	}

	eventLogConfFile, err := os.OpenFile(
		"./installer_output/config_eventlog.yml",
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0600,
	)
    if err != nil {
        return err
    }
	_, err = eventLogConfFile.WriteString("# Config file for the eventlog integration. Autogenerated with the Intaller Tool.\n\n")
	if err != nil {
        return err
    }
	_, err = eventLogConfFile.WriteString(string(eventLogConfYaml))
	if err != nil {
        return err
    }
	err = eventLogConfFile.Close()
	if err != nil {
        return err
    }

	return nil
}

func buildEventTypes(eventGroups []EventGroup) []string {
	eventTypes := []string{}
	for _, eventId := range eventGroups {
		switch eventId {
		case UserAccess:
			eventTypes = append(eventTypes,
				"Login",
				"LoginAs",
				"Logout",
			)
		case ApexUsage:
			eventTypes = append(eventTypes,
				"ApexCallout",
				"ApexExecution",
				"ApexRestApi",
				"ApexSoap",
				"ApexTrigger",
				"ApexUnexpectedException",
				"AuraRequest",
				"ConcurrentLongRunningApexLimit",
				"ExternalCustomApexCallout",
				"NamedCredential",
			)
		case LightningUsage:
			eventTypes = append(eventTypes,
				"LightningError",
				"LightningInteraction",
				"LightningLogger",
				"LightningPageView",
				"LightningPerformance",
				"VisualforceRequest",
			)
		case ApiAccess:
			eventTypes = append(eventTypes,
				"ApiTotalUsage",
				"BulkApi",
				"BulkApiRequest",
				"BulkApi2",
				"CompositeApi",
				"CompositeApiSubrequest",
				"MetadataApiOperation",
				"RestApi",
				"SoapApi",
			)
		case ReportAccess:
			eventTypes = append(eventTypes,
				"AsynchronousReportRun",
				"Dashboard",
				"MultiblockReport",
				"Report",
				"ReportExport",
			)
		case DocContentDbAccess:
			eventTypes = append(eventTypes,
				"DatabaseSave",
				"UniqueQuery",
				"DocumentAttachmentDownoads",
				"ContentDocumentLink",
				"ContentTransfer",
				"ContentDistribution",
			)
		case WaveUsage:
			eventTypes = append(eventTypes,
				"WaveChange",
				"WaveDownload",
				"WaveInteraction",
				"WavePerformance",
			)
		case ErrPermViol:
			eventTypes = append(eventTypes,
				"CorsViolation",
				"CspViolation",
				"InsufficientAccess",
				"PermissionUpdate",
				"InsecureExternalAssets",
				"TransactionSecurity",
				"BlockedRedirect",
				"HostnameRedirects",
				"GroupMembership",
			)
		}
	}
	return eventTypes
}

func setupOutputFolder() error {
	newpath := filepath.Join(".", "installer_output")
	os.MkdirAll(newpath, os.ModePerm)
	f, err := os.OpenFile(
		"./installer_output/.gitignore",
		os.O_RDWR|os.O_CREATE|os.O_TRUNC,
		0644,
	)
    if err != nil {
        return err
    }
	_, err = f.WriteString("*")
	if err != nil {
        return err
    }
	err = f.Close()
	if err != nil {
        return err
    }
	return nil
}