version: "2.0"
isTemplate: true  # Remove or set it to "false" after setting up all the options below

### Config for the Event Streamming integration

eventStream:
  integrationName: "com.newrelic.labs.sfdc.eventstream"
  auth:
    tokenUrl: "<TOKEN URL HERE>"
    userPass:
      clientId: "<CLIENT ID HERE>"
      clientSecret: "<CLIENT SECRET HERE>"
      username: "<USER NAME HERE>"
      password: "<PASSWORD HERE>"
  cache:  # Cache is optional, just remove it if you don't need de-duplication
    redis:
      host: "<REDIS SERVER HOST HERE>"
      port: 6379
      dbNumber: 0
      password: "<PASSWORD HERE or empty if no password>"
      expireDays: 1
  appetite: 50 # EDIT APPETITE HERE (maximum number of events to read per call)
  topics: # EDIT TOPICS HERE (events to capture)
    - "/event/LoginEventStream"
    - "/event/LogoutEventStream"
    - "/event/ReportEventStream"
    - "/event/ApiEventStream"
    - "/event/FileEvent"
    - "/event/UriEventStream"
    - "/event/LightningUriEventStream"

### Config for the New Relic client

licenseKey: "<LICENSE KEY HERE>"
accountId: "<ACCOUNT ID HERE>"
region: "<REGION HERE>" # either "EU" or "US"
format: "<FORMAT HERE>" # either "events" or "logs"