FROM golang:1.25.3-alpine3.22 AS build-stage

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 go build ./cmd/nr-salesforce-eventlog/nr-salesforce-eventlog.go

FROM alpine:3.22 AS release-stage

WORKDIR /app

COPY --from=build-stage /build/nr-salesforce-eventlog ./

# EDIT, if necessary
COPY event_type_fields.yml ./

# EDIT, if necessary
COPY config.yml ./

CMD ["./nr-salesforce-eventlog"]
