from dataclasses import dataclass

@dataclass
class Text:
    # Question description
    desc: str
    # Question prompt
    prom: str

t_integration_name = Text(
    desc = "Identifier used in logs generated by the exporter. Default `com.newrelic.labs.sfdc.eventlogfiles`",
    prom = "Integration name?"
)

t_run_as_service = Text(
    desc = """Enable the built-in scheduler.
If set to Yes, the integration will run continuously as a service and self-schedule executions.
If set to No, the integration will run once and finish, so scheduling must be done externally.
Default `N`.""",
    prom = "Run as a service (y/n)?"
)

t_cron_interval = Text(
    desc = "The execution interval (in minutes) used by the external scheduler. Default 60.",
    prom = "Cron interval (1-10000)?"
)

t_conf_scheduler = Text(
    desc = "Service schedule configuration.",
    prom = "Do you want to set up a service schedule (y/n)?"
)

t_service_scheduler_hours = Text(
    desc = "Service schedule hours. Either '*' or comma separated hours (0-23) when the integration must fire.",
    prom = "Hours?"
)

t_service_scheduler_mins = Text(
    desc="Service schedule minutes. Either '*' or comma separated minutes (0-59) when the integration must fire.",
    prom="Minutes?"
)

t_num_instances = Text(
    desc = "Salesforce instances",
    prom = "How many instances do you want to set up (1-10)?"
)